"$schema" = 'https://starship.rs/config-schema.json'

# format = "$username\\($hostname\\)$fill$directory$cmd_duration\n\r$character"
# right_format = """$directory$cmd_duration"""
format = "$directory$hostname$fill$all$character"
right_format = "$cmd_duration"

[fill]
symbol = ' '

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = true
show_always = true

[username.aliases]
cangs = "ibldzn"

[hostname]
ssh_only = true
ssh_symbol = "  "
format = 'on [$ssh_symbol$hostname](bold yellow) '
disabled = false

[character]
success_symbol = "[󰣇](bold blue)"
error_symbol = "[󰣇](bold red)"

[directory]
read_only = " 󰌾"
truncation_length = 10
truncate_to_repo = true

[cmd_duration]
min_time = 1000
format = "[$duration](bold yellow)"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = "󰢱 "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./.venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
